package conformance

// Field order is the frozen A1/A4/C1-C5 wire allocation, not proto JSON order.
var snapshotQueryFields = map[string]string{
	"SnapshotPin":                         "network_id:string keeper_shard_id:uint32 snapshot_id:string safe_block_seq:uint64 manifest_root:string state_root:string schema_snapshot_id:string schema_root:string",
	"SnapshotReadPart":                    "table_id:string partition_id:string part_name:string part_phys_hash:string part_row_lthash:string row_count:uint64 bytes:uint64",
	"SnapshotReadTable":                   "database:string table:string table_id:string schema_hash:string partition_roots:[]PartitionCommitment active_parts:[]SnapshotReadPart",
	"SnapshotReadSet":                     "read_snapshot:SnapshotPin tables:[]SnapshotReadTable",
	"SnapshotQueryBinding":                "envelope_version:uint32 input_kind:string client_account:string statement_id:string statement_kind:uint32 network_id:string keeper_shard_id:uint32 sql_hash:string settings_hash:string target_table_id:string schema_hash:string row_id_profile_id:string client_revision:uint32 read_snapshot:SnapshotPin read_set_root:string schema_snapshot_id:string schema_root:string logical_database:string query_profile_id:string executor_profile_id:string reservation_id:string fencing_generation:uint64",
	"SnapshotQueryInput":                  "binding:SnapshotQueryBinding sql:string read_set:SnapshotReadSet",
	"SnapshotQueryEnvelope":               "input:SnapshotQueryInput input_root:string user_jws:string",
	"SnapshotQueryReservation":            "reservation_id:string fencing_generation:uint64 client_account:string statement_id:string read_snapshot:SnapshotPin executor_profile_id:string query_profile_id:string activation_id:string",
	"SnapshotQueryReservationStatus":      "version:uint32 found:bool state:string request_id:string client_account:string statement_id:string fencing_generation:uint64 reservation:SnapshotQueryReservation block_seq:uint64 terminal_proof:bytes",
	"SnapshotQueryStatement":              "statement_seq:uint64 envelope:SnapshotQueryEnvelope",
	"SnapshotQueryJob":                    "block_seq:uint64 prev_safe_snapshot_id:string prev_state_root:string schema_snapshot_id:string executor_profile_id:string query_profile_id:string reservation:SnapshotQueryReservation statement:SnapshotQueryStatement source_claim_root:string source_claim:SnapshotQueryClaim",
	"SnapshotQueryEvidence":               "execution_outcome:string output_row_count:uint64 output_rows_root:string",
	"SnapshotQueryReceipt":                "block_seq:uint64 statement_root:string input_root:string read_set_root:string read_snapshot:SnapshotPin schema_snapshot_id:string executor_profile_id:string query_profile_id:string reservation_id:string fencing_generation:uint64 execution_outcome:string abort_record_root:string output_row_count:uint64 output_rows_root:string source_claim_root:string computed_state_root:string match_source_root:bool partition_commitments_after:[]PartitionCommitment affected_parts:[]PartManifestEntry replay_log_hash:string",
	"SnapshotQueryAttestation":            "replica_id:string receipt:SnapshotQueryReceipt receipt_hash:string signature:string",
	"SnapshotQuerySubmitResult":           "admission_code:uint32 message:string statement_seq:uint64 block_seq:uint64 source_node:string input_root:string reservation:SnapshotQueryReservation",
	"SnapshotQueryStatus":                 "version:uint32 found:bool accepted:SnapshotQuerySubmitResult lifecycle:string execution_outcome:string terminal_proof:bytes",
	"ActiveQueryPolicy":                   "activation_id:string network_id:string keeper_shard_id:uint32 activation_block_seq:uint64 executor_profile_id:string query_profile_id:string enabled:bool",
	"ExecutorProfileTransition":           "network_id:string keeper_shard_id:uint32 prev_snapshot_id:string prev_state_root:string old_executor_profile_id:string new_executor_profile_id:string schema_snapshot_id:string schema_root:string data_root:string next_snapshot_id:string next_state_root:string next_manifest_root:string activation:ActiveQueryPolicy",
	"ExecutorProfileTransitionReceipt":    "transition_root:string replica_id:string signature:string",
	"SnapshotArtifactReady":               "snapshot_id:string manifest_root:string schema_root:string artifact_set_root:string publisher_id:string retention_policy_id:string",
	"SnapshotQueryAbortRecord":            "block_seq:uint64 statement_id:string input_root:string reservation_id:string fencing_generation:uint64 reason_code:string cleanup_authorization_root:string prev_snapshot_id:string next_snapshot_id:string",
	"SnapshotQueryClaim":                  "source_node:string statement_id:string statement_seq:uint64 block_seq:uint64 input_root:string reservation_id:string fencing_generation:uint64 execution_outcome:string output_row_count:uint64 output_rows_root:string computed_state_root:string partition_deltas:[]PartitionCommitment partition_commitments_after:[]PartitionCommitment candidate_parts:[]SnapshotReadPart",
	"ProfileSetting":                      "name:string value:string",
	"QueryLimits":                         "max_sql_bytes:uint64 max_descriptor_bytes:uint64 max_output_rows:uint64 max_output_bytes:uint64 max_restore_bytes:uint64 max_sort_memory_bytes:uint64 max_spill_bytes:uint64 max_execution_ms:uint64",
	"QueryProfileRecord":                  "version:uint32 clickhouse_build_digest:string platform:string native_analyzer_build_digest:string grpc_analyzer_build_digest:string tzdata_digest:string settings:[]ProfileSetting scalar_operators:[]string column_profile_id:string output_order_id:string limits:QueryLimits",
	"SnapshotQueryControlBinding":         "operation:string network_id:string keeper_shard_id:uint32 client_account:string statement_id:string request_id:string reservation_id:string fencing_generation:uint64",
	"AcquireSnapshotQueryRequest":         "network_id:string keeper_shard_id:uint32 client_account:string statement_id:string request_id:string control_jws:string",
	"GetSnapshotQueryReservationRequest":  "network_id:string keeper_shard_id:uint32 client_account:string statement_id:string request_id:string control_jws:string reservation_id:string fencing_generation:uint64",
	"ReleaseSnapshotQueryRequest":         "network_id:string keeper_shard_id:uint32 client_account:string statement_id:string request_id:string control_jws:string reservation_id:string fencing_generation:uint64",
	"GetSnapshotQueryStatusRequest":       "network_id:string keeper_shard_id:uint32 client_account:string statement_id:string expected_input_root:string expected_user_jws_hash:string",
	"SnapshotBarrier":                     "state:string generation:uint64 request_id:string client_account:string statement_id:string reservation:SnapshotQueryReservation block_seq:uint64",
	"SnapshotArtifactReadySubmission":     "record:SnapshotArtifactReady signature:string",
	"GetPublishedSnapshotRequest":         "network_id:string keeper_shard_id:uint32 snapshot_id:string",
	"PublishedSnapshot":                   "manifest:SafeSnapshotManifest activation:ActiveQueryPolicy artifact_ready:SnapshotArtifactReadySubmission terminal_proof:bytes",
	"GetQueryPolicyRequest":               "network_id:string keeper_shard_id:uint32 activation_id:string block_seq:uint64",
	"QueryPolicyStatus":                   "found:bool activation:ActiveQueryPolicy terminal_proof:bytes",
	"SnapshotArtifactEntry":               "table_id:string partition_id:string part_name:string part_phys_hash:string object_digest:string bytes:uint64",
	"SnapshotArtifactSet":                 "parts:[]SnapshotArtifactEntry schema_artifact_digest:string",
	"BeginSnapshotQueryCmd":               "request:AcquireSnapshotQueryRequest",
	"GrantSnapshotQueryCmd":               "request_id:string reservation:SnapshotQueryReservation",
	"ReleaseSnapshotQueryCmd":             "request:ReleaseSnapshotQueryRequest",
	"SubmitSnapshotQueryCmd":              "envelope:SnapshotQueryEnvelope non_membership_proof:bytes",
	"AbortSnapshotQueryCmd":               "record:SnapshotQueryAbortRecord authority_jws:string",
	"ActivateQueryProfileCmd":             "activation:ActiveQueryPolicy authority_jws:string",
	"RecordSnapshotQueryClaimCmd":         "claim:SnapshotQueryClaim",
	"RecordSnapshotQueryAttestationCmd":   "attestation:SnapshotQueryAttestation",
	"PublishExecutorProfileTransitionCmd": "transition:ExecutorProfileTransition manifest:SafeSnapshotManifest receipts:[]ExecutorProfileTransitionReceipt authority_jws:string",
	"RecordSnapshotArtifactReadyCmd":      "submission:SnapshotArtifactReadySubmission",
	"ReplayTableSchema":                   "table_id:string schema_json:string",
	"ReplayTableSetTransition":            "adds:[]ReplayTableSchema retires:[]string new_schema_root:string",
}
